<?xml version="1.0" encoding="utf-8"?><Database Name="KaygeryaCms" Class="CMSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=Mehmetakn-PC\SQLEXPRESS;Initial Catalog=KaygeryaCms;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="KaygeryaCmsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PageOptions" Member="PageOptions">
    <Type Name="PageOption">
      <Column Name="PageOptionID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PageID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PageKey" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PageValue" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Page_PageOption" Member="Page" ThisKey="PageID" OtherKey="PageID" Type="Page" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Pages" Member="Pages">
    <Type Name="Page">
      <Column Name="PageID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PageTitle" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="ParentPage" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SeoTitle" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="SeoDescription" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Keywords" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="PageContent" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="PageOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Page_PageOption" Member="PageOptions" ThisKey="PageID" OtherKey="PageID" Type="PageOption" />
      <Association Name="Page_Page" Member="Pages" ThisKey="PageID" OtherKey="ParentPage" Type="Page" />
      <Association Name="Page_Page" Member="Page1" ThisKey="ParentPage" OtherKey="PageID" Type="Page" IsForeignKey="true" />
    </Type>
  </Table>
</Database>